const LISTINGS=[{name:"The Bellavue Residences",district:"Life Camp",type:"Apartment / new residential",price:"From ₦80m (confirm)",note:"Public listing historically shown as luxury Life Camp residences."},{name:"The Hills Residences",district:"Guzape",type:"Residential development",price:"Premium band",note:"Guzape hillside product. Demo card only."},{name:"Brick City Valley",district:"Kubwa",type:"3-bed semi-detached duplex",price:"Mid-market",note:"Family product in Kubwa. Availability must be confirmed."},{name:"Urban Shelter Estate",district:"Kyami",type:"2-bed semi-detached",price:"Entry / mid",note:"Kyami estate for first-home and investor tickets."},{name:"Urban Shelter Square",district:"Garki",type:"Commercial / retail",price:"On request",note:"Garki commercial floor plates."},{name:"Kubwa Mall",district:"Kubwa",type:"Commercial",price:"On request",note:"Retail investment sample."}];
const seedLeads=[{t:"Sun 21:14",name:"Tunde (UK)",district:"Guzape",intent:"invest",score:"Hot",next:"Video tour pack + Hills brochure"},{t:"Sat 19:02",name:"Aisha Bello",district:"Kyami",intent:"buy",score:"Warm",next:"Payment plan FAQ + Sat slot"},{t:"Fri 13:40",name:"Chinedu Okeke",district:"Kubwa",intent:"buy",score:"Cold",next:"Nurture +48h if silent"}];
function scoreLead(d){let pts=40;if(d.timeline==="now")pts+=30;if(d.timeline==="90")pts+=18;if(d.timeline==="research")pts-=15;if(Number(d.budget)>=80)pts+=15;if(d.buyer==="diaspora")pts+=12;if(d.intent==="invest"||d.intent==="buy")pts+=8;if(pts>=75)return"Hot";if(pts>=55)return"Warm";return"Cold";}
function matchListing(d){return LISTINGS.find(l=>l.district===d.district)||LISTINGS[0];}
function replyCopy(d,score,match){return `Good day ${d.name.split(" ")[0]}, thank you for Urban Shelter.\n\nYou are looking to ${d.intent} in ${d.district}. Closest public match in this demo: ${match.name} (${match.type}).\n\nLead score: ${score}.\nNext question: physical inspection or diaspora video tour this week?\n\nThis is a prototype reply — not sent from Urban Shelter systems.`;}
function renderListings(filter){document.getElementById("listingGrid").innerHTML=LISTINGS.filter(l=>filter==="all"||l.district===filter).map(l=>`<article class="listing"><small>${l.district}</small><h3>${l.name}</h3><div class="price">${l.price}</div><p>${l.type}</p><p>${l.note}</p><a class="btn primary" href="#inspect">Request inspection</a></article>`).join("");}
function renderTable(){const leads=JSON.parse(localStorage.getItem("us_leads")||"null")||seedLeads;document.getElementById("leadTable").innerHTML=leads.map(l=>`<tr><td>${l.t}</td><td>${l.name}</td><td>${l.district}</td><td>${l.intent}</td><td><span class="badge ${l.score.toLowerCase()}">${l.score}</span></td><td>${l.next}</td></tr>`).join("");}
document.querySelectorAll(".filters button").forEach(btn=>{btn.addEventListener("click",()=>{document.querySelectorAll(".filters button").forEach(b=>b.classList.remove("on"));btn.classList.add("on");renderListings(btn.dataset.filter);});});
document.getElementById("leadForm").addEventListener("submit",e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries());const score=scoreLead(data);const match=matchListing(data);const copy=replyCopy(data,score,match);const box=document.getElementById("qualifier");const wa=encodeURIComponent(`Hello Urban Shelter sales, I am ${data.name}. I want to ${data.intent} in ${data.district}. Please share current availability for ${match.name}.`);box.classList.remove("empty");box.innerHTML=`<h3>Qualifier result</h3><p><span class="badge ${score.toLowerCase()}">${score}</span> · match: <b>${match.name}</b></p><p>${data.buyer==="diaspora"?"Diaspora path: video tour + document pack.":"Local path: lock inspection within 48 hours."}</p><pre style="white-space:pre-wrap;font:inherit;background:#fff;padding:12px;border:1px solid #d9cfc0">${copy}</pre><p><b>3-touch plan</b><br>Now: this message.<br>+4h: payment plan / title FAQ if no reply.<br>+48h: assign to sales desk.</p><a class="wa" href="https://wa.me/2348110455824?text=${wa}" target="_blank" rel="noopener">Preview WhatsApp click-to-chat</a>`;const leads=JSON.parse(localStorage.getItem("us_leads")||"null")||seedLeads.slice();leads.unshift({t:new Date().toLocaleString("en-NG",{hour:"2-digit",minute:"2-digit",weekday:"short"}),name:data.name,district:data.district,intent:data.intent,score,next:score==="Hot"?"Call / WA in 15 min":score==="Warm"?"Nurture + book slot":"48h drip"});localStorage.setItem("us_leads",JSON.stringify(leads.slice(0,12)));renderTable();});
document.getElementById("inspectForm").addEventListener("submit",e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target).entries());document.getElementById("inspectResult").innerHTML=`<div class="card" style="margin-top:16px"><h3>Inspection hold (demo)</h3><p><b>${d.name}</b> · ${d.project}<br>${d.date} · ${d.slot}</p><p>Reminders: T-24h WhatsApp, T-2h WhatsApp, no-show reschedule link.</p><p>Assigned agent (example): Sales desk · sales@urbanshelter.com</p></div>`;});
renderListings("all");renderTable();
